name: Hotfix workflow

on:
  push:
    branches: [hotfix_*]

jobs:
  build:
    name: Test checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - run: |
          ls -al
