name: Pull request workflow

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Test checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: |
          ls -al
